#!/usr/bin/env ruby

require "rubeme"

def usage
  puts <<HELP
usage:
    rubeme [option] [FILE]
option:
    -d, --debug   : specify to run in verbose mode
    -v, --version : print version
    -h, --help    : show this message
HELP
end

def print_version
  puts Rubeme.make_version("rubeme")
end

opts = {}

while ARGV.size > 0
  arg = ARGV.shift
  case arg
  when "-d", "--debug"
    opts[:verbose] = true
  when "-v", "--version"
    print_version
    exit 0
  when "-h", "--help"
    usage
    exit 0
  else
    opts[:files] ||= []
    opts[:files] << arg
  end
end

puts "Bye!"
